//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Product
    {
        [Key]
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name of product is required")]
        [Display(Name = "Product Name")]
        [MaxLength(50)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Category of product is required")]
        [Display(Name = "Category")]
        [MaxLength(50)]
        public string Category { get; set; }

        [Required(ErrorMessage = "Price of product is required")]
        [Display(Name = "Price")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Quantity of product is required")]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Enter short description of the product here")]
        [Display(Name = "Short Description")]
        public string Short_Description { get; set; }

        [Display(Name = "Long Description")]
        public string Long_Description { get; set; }

        [Required(ErrorMessage = "Enter small image of the product here")]
        [Display(Name = "Small Image")]
        public string Small_ImagePath { get; set; }

        [Display(Name = "Large Image")]
        public string Large_ImagePath { get; set; }
    }
}
